CREATE DATABASE IF NOT EXISTS bancosjubs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bancosjubs;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,         -- armazena hash via password_hash()
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;